### ISSUE TITLE
Use double quotes when using -p flag

### ISSUE THREAD

**Issue by markphd** [Newsman/MailToJson#2]
I'm trying to convert EML file to JSON using the -p flag, but the printed output uses single quotes which makes the JSON document invalid.

```
Error: Parse error on line 2:
{'attachments': [], 
-^
Expecting 'STRING', '}', got 'undefined'
```

If I edit the file and change surrounding quotes to double quotes, it can parse the JSON document correctly. Is there any workaround?

**Comment by dazoot** [comment]
The -p output is NOT json. It's pretty print from Python: https://docs.python.org/2/library/pprint.html
