### ISSUE TITLE
script is not working properly with latest postfix

### ISSUE THREAD

**Issue by milenmit** [Newsman/MailToJson#7]
using python2.
{
  "from": null,
  "attachments": [],
  "to": null,
  "cc": null,
  "encoding": "utf-8",
  "datetime": "2023-09-25 19:54:41",
  "headers": {},
  "parts": [
    {
      "content": "Xxxxxxxxxxxx whole mail content is placed here",
      "headers": {},
      "content_type": "text/plain"
    }
  ],
  "reply-to": null,
  "subject": ""
}

**Comment by dazoot** [comment]
What postfix version ?

**Comment by dazoot** [comment]
need more details to investigate.
